server {
    host        127.0.0.1;
    port        8080;
    server_name localhost;
    max_body_size 200M;
    error_page  404 /errors/404.html;
    error_page  500 /errors/500.html;

    location / {
        root            ./www;
        index           index.html;
        methods         GET;
        directory_listing off;
    }

    location /directory {
        root            ./www/YoupiBanane;
        index           youpi.bad_extension;
        methods         GET POST;
        directory_listing off;
        cgi             .bla ./www/cgi-bin/cgi_tester;
    }

    location /post_body {
        methods         POST;
        max_body_size   100;
        root            ./www/post_body;
    }

    location /upload {
        root            ./www/uploads;
        methods         GET POST DELETE;
        upload_dir      ./www/uploads;
        max_body_size   10M;
    }

    location /cgi-bin {
        root            ./www/cgi-bin;
        methods         GET POST;
        cgi             .php /usr/bin/php-cgi;
        cgi             .py /usr/bin/python3;
        cgi             .bla ./www/cgi-bin/cgi_tester;
    }

    location /old {
        redirect        http://127.0.0.1:8080/;
        methods         GET;
    }
}

server {
    host        127.0.0.1;
    port        8080;
    server_name example.com;
    error_page  404 /errors/404.html;

    location / {
        root            ./www;
        index           index.html;
        methods         GET;
        directory_listing off;
    }
}

server {
    host        127.0.0.1;
    port        9090;
    error_page  404 /errors/404.html;

    location / {
        root            ./www;
        index           index.html;
        methods         GET;
        directory_listing on;
    }
}